### ISSUE TITLE
Getting this error when starting nvim 

### ISSUE THREAD

**Issue by Dan1jel** [AyeSpacey/Nvimfy#1]
![Screenshot_20210920-105328](https://user-images.githubusercontent.com/4266424/133977644-b988befa-ae2b-4900-8f45-0949dd61d156.png)

**Comment by AyeSpacey** [comment]
remove the lua require('base') line from init.vim

**Comment by AyeSpacey** [comment]
and you may re-add this line
to use treesitter features
type it yourself don't cut paste..
