### ISSUE TITLE
got termux error while installing using script

### ISSUE THREAD

**Issue by KunalSingh19** [AyeSpacey/Nvimfy#11]
_______       _         ___                                  (_______)     (_)       / __)
    _     _ _   _ _ ____ _| |__ _   _
   | |   | | | | | |    (_   __) | | |                           | |   | |\ V /| | | | || |  | |_| |
   |_|   |_| \_/ |_|_|_|_||_|   \__  |
                                  /_/
-------------------------------------------

Wait for the plugins to be installed,                         then Reload Neovim...
                                                              Launching Neovim-(Nvimfied) !
./install.sh: line 80: nvim: command not found
No command Credits found, did you mean:
 Command bvedit in package bvi
 Command mcedit in package mc
 Command recins in package recutils                            Command redir in package redir
~ $

**Comment by AyeSpacey** [comment]
Neovim is not installed... Install it first
